In [1]:
5+5

10

In [2]:
My first comment

In [4]:
f = lambda x, y: x**2 + y
print(f(3, 1))

10


In [5]:
def e_potentielle(masse, hauteur, g):
    E = masse * hauteur * g
    print(E, "Joules")
e_potentielle(200, 1.80, 9.81)

3531.6000000000004 Joules


In [13]:
def signe(x):
    if x > 0:
        print(x, 'positif')
    elif x < 0:
        print(x, 'negatif')
    else:
        print(x, 'nul')

In [16]:
signe(-1)

-1 negatif


In [18]:
for i in range(5, 10, 2):
    print('Bonjour')

Bonjour
Bonjour
Bonjour


In [19]:
villes = ["Brazzaville", "Pointe-Noire", "Dolisie", "Oyo", "Libreville"]

In [20]:
len(villes)

5

In [21]:
villes.count("Brazzaville")

1

In [22]:
for index, value in enumerate(villes):
    print(index, value)

0 Brazzaville
1 Pointe-Noire
2 Dolisie
3 Oyo
4 Libreville


In [23]:
if "Brazzaville" in villes:
    print("Oui")
else:
    print("Non")

Oui


In [26]:
traduction = {
    "chien": "Dog",
    "chat": "Cat",
    "ordinateur": "Computer"
}

for keys, values in traduction.items():
    print(keys,':',values)

chien : Dog
chat : Cat
ordinateur : Computer


In [27]:
traduction.keys()

dict_keys(['chien', 'chat', 'ordinateur'])

In [28]:
traduction.values()

dict_values(['Dog', 'Cat', 'Computer'])

## Fonctions

In [30]:
x = -1

abs(x)

1

In [31]:
y = 3.14

abs(y)

3.14

In [33]:
round(y)

3

In [36]:
liste_1 = [1, 2, 3, 4, 5, 6, 7]

In [37]:
max(liste_1)

7

In [38]:
min(liste_1)

1

In [39]:
sum(liste_1)

28

## Conversions

In [40]:
x = 10

type(x)

int

In [41]:
x = str(x)

x

'10'

In [42]:
tuple(liste_1)

(1, 2, 3, 4, 5, 6, 7)

## Fichiers

In [45]:
f = open('fichier.txt', 'w')

f.write("Bonjour")
f.close()

In [1]:
f = open('fichier.txt', 'r')
print(f.read())
f.close()

Bonjour


## Modules et Importations

In [7]:
from math import *

c = cos(90)

s = sin(90)

print(c)

print(s)

-0.4480736161291701
0.8939966636005579


In [10]:
import statistics

liste_1 = [1, 2, 3, 4]

print(statistics.variance(liste_1))

1.6666666666666667


In [11]:
print(statistics.mean(liste_1))

2.5


In [13]:
import random

print(random.choice(liste_1))

2


In [15]:
random.seed(0)
print(random.choice(liste_1))

4


In [16]:
print(random.choice(liste_1))

4


In [17]:
print(random.choice(liste_1))

1


In [19]:
import os

os.getcwd()

'C:\\Users\\Rostaing\\Desktop\\Python-Anaconda'

In [21]:
import glob

print(glob.glob("*"))

['fichier.txt', 'first_python_test.ipynb']


In [22]:
print(glob.glob("*.txt"))

['fichier.txt']


## Package Numpy

In [1]:
import numpy as np

A = np.array([1, 2, 3])
A.ndim

1

In [4]:
A = np.array([1, 2, 3])
A.shape

(3,)

In [9]:
B =  np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.random.seed(0)
D = np.full((2,3), 9)

In [1]:
np.random.randn(3, 4, dtype=np.float16)

NameError: name 'np' is not defined

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [29]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [40]:
np.hstack((B, C))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [41]:
H = np.hstack((B, C))
H.shape

(3, 6)

In [7]:
import numpy as np
J = np.zeros((2,3))
K = np.ones((2,3))
G = np.concatenate((J, K), axis=0)
G

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
G.ndim

2

In [9]:
G.shape

(4, 3)

In [10]:
G.size

12

In [11]:
G[0, 0]

0.0

In [12]:
G[2, 2]

1.0

## Indexing Slicing Masking

In [13]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
A.ndim

2

In [15]:
A.shape

(3, 3)

In [16]:
A.size

9

In [17]:
A[0, 0]

1

In [18]:
A[1, 1]

5

In [19]:
A[:, 0]

array([1, 4, 7])

In [20]:
A[0, :]

array([1, 2, 3])

In [21]:
A[:, 1]

array([2, 5, 8])

In [28]:
A[0:2, 0:2] = 10

A

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [23]:
A[0]

array([1, 2, 3])

In [84]:
A[:, -2:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [69]:
A[0:2]

array([[10, 10,  3],
       [10, 10,  6]])

In [85]:
T = np.zeros((5, 5))
T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
T[::2, ::2] = 1

In [87]:
T

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [88]:
P = np.random.randint(0, 10, [5, 5])
P

array([[5, 1, 4, 1, 0],
       [8, 0, 6, 1, 8],
       [6, 4, 0, 9, 3],
       [4, 8, 1, 8, 3],
       [5, 2, 3, 1, 7]])

In [12]:
P[P < 5] = 10
P

NameError: name 'P' is not defined

## Boolean Indxing

In [90]:
Y = np.random.randint(0, 7, [4, 4])

Y

array([[5, 5, 6, 4],
       [5, 0, 6, 6],
       [3, 5, 3, 4],
       [5, 2, 6, 4]])

In [98]:
Y[(Y<=4) & (Y>=6)] = 1

Y

array([[1, 1, 6, 1],
       [1, 1, 6, 6],
       [1, 1, 1, 1],
       [1, 1, 6, 1]])

## Méthodes ndarray(axis=0  => axe vertical et axis = 1  => axe horizontal)

In [101]:
np.random.seed(0)
I = np.random.randint(0, 10, [2, 3])
I

array([[5, 0, 3],
       [3, 7, 9]])

In [104]:
I.sum()

27

In [105]:
I.sum(axis=0)

array([ 8,  7, 12])

In [106]:
I.sum(axis=1)

array([ 8, 19])

In [107]:
np.exp(I)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

## Statistiques

In [108]:
R = np.array([[5, 0], [3, 7]])
R = np.array([[5, 0, 3], [3, 7, 9]])
R

array([[5, 0, 3],
       [3, 7, 9]])

In [109]:
R.mean() # La moyenne

4.5

In [110]:
R.std() # L'écart type

2.9297326385411577

In [111]:
R.var() # La variance

8.583333333333334

In [112]:
np.corrcoef(R) # Fonction de correlation

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [113]:
np.corrcoef(R)[0, 1]

-0.5636214801906779

In [116]:
np.unique(R, return_counts=True)


(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [117]:
values, counts = np.unique(R, return_counts=True)
counts

array([1, 2, 1, 1, 1], dtype=int64)

In [118]:
counts.argsort()

array([0, 2, 3, 4, 1], dtype=int64)

In [1]:
g = lambda x, y: x**3 + y**2 + 1
print(g(1, 1))

3


In [2]:
range(10)

range(0, 10)

In [3]:
print(range(10))

range(0, 10)


In [5]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [19]:
for i in range(10, 0, -2):
    print(i)

10
8
6
4
2


In [17]:
# Affiche les nombres pairs inférieurs à une valeur donnée

n=int(input("Donnez un nombre: "))

while n!=0:
    for i in range(0, n, 2):
        print(i, end="\t")
    
    n = int(input("\n Donnez un nombre: "))
    print("")

Donnez un nombre: 12
0246810Donnez un nombre: 14
024681012Donnez un nombre: 5
024Donnez un nombre: 7
0246Donnez un nombre: 2
0Donnez un nombre: 0


# Les listes 

In [35]:
# Création de la liste
L = [1, 2, "Maty", True, "False", False, 2+3j, 3.14]
L

[1, 2, 'Maty', True, 'False', False, (2+3j), 3.14]

In [76]:
# Suppression des éléments de la lise et la liste
del L[2]
L

[1, 2, 1, 4, 2, 8, 10]

In [ ]:
# Suppression des éléments de la lise et renvoi un la liste vide
L.clear()

In [31]:
# Afficher un élément de la liste
L[2]

'Maty'

In [37]:
# Remplacer un élément
L[3] = "Maman"
L

[1, 2, 'Maty', 'Maman', 'False', False, (2+3j), 3.14]

In [38]:
len(L)

8

In [44]:
# Ajouter un élément à la fin de la liste
L.append(5)
L

[1, 2, 'Maty', 'Maman', 'False', False, (2+3j), 3.14, 5, 5, 5, 5, 5]

In [47]:
# Inserer un élément dans la liste
L.insert(0, 100)
L

[100,
 100,
 100,
 1,
 2,
 'Maty',
 'Maman',
 'False',
 False,
 (2+3j),
 3.14,
 5,
 5,
 5,
 5,
 5]

In [48]:
# Etendre la liste

L.extend([4, 5, 6, "IAI", 13])
L

[100,
 100,
 100,
 1,
 2,
 'Maty',
 'Maman',
 'False',
 False,
 (2+3j),
 3.14,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 6,
 'IAI',
 13]

In [49]:
L.insert(len(L), "zero")
L

[100,
 100,
 100,
 1,
 2,
 'Maty',
 'Maman',
 'False',
 False,
 (2+3j),
 3.14,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 6,
 'IAI',
 13,
 'zero']

In [50]:
L.insert(len(L)+1, "un")
L

[100,
 100,
 100,
 1,
 2,
 'Maty',
 'Maman',
 'False',
 False,
 (2+3j),
 3.14,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 6,
 'IAI',
 13,
 'zero',
 'un']

In [57]:
# Suppression des éléments dans la liste
L = [1, 2, 3, 6, 8, 10]
L.remove(3)
L

[1, 2, 6, 8, 10]

In [58]:
# Suppression du dernier un élément de la liste
L.pop()
L

[1, 2, 6, 8]

In [59]:
# Autre manière de supprimer la liste avec pop()
L.pop(3)

8

In [69]:
# Vérification d'appartenance d'un élément dans une liste
3 in L

False

In [70]:
# Vérification d'appartenance d'un élément dans une liste
8 in L

False

In [71]:
# Compter le nombre d'un élémnet dans une liste
L.count(1)

1

In [82]:
L = L + [3, 1, 4, 2, 8, 10]
L

[1, 2, 1, 4, 2, 8, 10, 3, 4, 2, 8, 10, 3, 1, 4, 2, 8, 10]

In [74]:
L.count(2)

2

In [77]:
# Afficher une partie de la liste sans utiliser les boucles, le slasing
L[2:5]


[1, 4, 2]

In [78]:
L[2:]

[1, 4, 2, 8, 10]

In [79]:
L[:3]

[1, 2, 1]

In [81]:
L[::2]

[1, 1, 2, 10, 4, 8]

In [84]:
L[1::2]

[2, 4, 8, 3, 2, 10, 1, 2, 10]

In [85]:
L[-1]

10

In [86]:
L[-5]

1

In [87]:
L[-4:]

[4, 2, 8, 10]

In [90]:
L[-3:-1]

[2, 8]

In [91]:
L[-3:]

[2, 8, 10]

In [92]:
L[-5]

1

In [95]:
# Nouvelle liste
L1 = [1, 2, 3, 6, 8, 10]
L1

[1, 2, 3, 6, 8, 10]

In [97]:
L1[len(L1)-5]

2

In [100]:
del L1[-5:]
L1

[]

In [103]:
L1[-5:] = []
L1

[]

In [105]:
A = [1, 3, 5, 7, 10]
A

[1, 3, 5, 7, 10]

In [106]:
# Référence
B = A
B

[1, 3, 5, 7, 10]

In [107]:
# Copie
C = A[::]
C

[1, 3, 5, 7, 10]

In [108]:
# Cppie
D = A.copy()
D

[1, 3, 5, 7, 10]

In [109]:
B[0] = 2
A

[2, 3, 5, 7, 10]

In [110]:
C

[1, 3, 5, 7, 10]

In [111]:
D

[1, 3, 5, 7, 10]

In [116]:
D[0] = 9

In [120]:
L = [0, 1, 2, 3, 4]
L

[0, 1, 2, 3, 4]

In [122]:
A = L + [5]
A

[0, 1, 2, 3, 4, 5]

In [126]:
A = []
for e in L:
    A.append(e*e)
A

[0, 1, 4, 9, 16]

In [127]:
# Comprehension d'une liste
B = [e**2 for e in L]
B

[0, 1, 4, 9, 16]

In [128]:
# Comprehension d'une liste
C = [e for e in L if e%2==0]
C

[0, 2, 4]

In [129]:
# Les fonctions: zip
A = ['Gabon', 'Congo', 'Tchad', 'Burkina']
B = ['Libreville', 'Brazzaville', "N'djamena", 'Ouagadougou']

In [131]:
A

['Gabon', 'Congo', 'Tchad', 'Burkina']

In [132]:
B

['Libreville', 'Brazzaville', "N'djamena", 'Ouagadougou']

In [133]:
C = zip(A, B)
C

In [134]:
C = list(zip(A, B))
C

[('Gabon', 'Libreville'),
 ('Congo', 'Brazzaville'),
 ('Tchad', "N'djamena"),
 ('Burkina', 'Ouagadougou')]

In [135]:
for p, c in C:
    print(p, "a pour capitale", c)

Gabon a pour capitale Libreville
Congo a pour capitale Brazzaville
Tchad a pour capitale N'djamena
Burkina a pour capitale Ouagadougou


# Les tuples

In [136]:
# - Ordonnée
# - Inchangeable

T = (1, 2)
T

(1, 2)

In [138]:
# Modification du tuple
T = T + (3,)
T

(1, 2, 3)

In [140]:
# Ajout des valeur dans un tuple
T = T + (3, 2, 1, 3, 5, 1)
T

(1, 2, 3, 3, 2, 1, 3, 5, 1)

In [141]:
# Compter un élément dans un tuple
T.count(1)

3

In [142]:
T.index(5)

7

In [143]:
for i in T:
    print(i)

1
2
3
3
2
1
3
5
1


In [144]:
L = [e for e in T]
L

[1, 2, 3, 3, 2, 1, 3, 5, 1]

In [146]:
# Convertion du tuple en liste
B = list(T)
B

[1, 2, 3, 3, 2, 1, 3, 5, 1]

In [147]:

help(T.index)

Help on built-in function index:

index(value, start=0, stop=9223372036854775807, /) method of builtins.tuple instance
    Return first index of value.
    
    Raises ValueError if the value is not present.



In [153]:
n = len(T)
i = 0

a = int(input("Donnez un entier: "))
while i < n:
    if (T[i] == a):
        print(a, "indice", i)
    i+=1
    

Donnez un entier: 12


# Les dictionnaires

In [1]:
B = {'a', 'b', 'o', 1, 2, 0, 'a', 'c'}
A = {'c', 1, 2, 'e', 'f'}

for e in B: print(e)

0
a
2
1
o
c
b


In [3]:
for e in B: print(e, end="")

0a21ocb

In [4]:
C = B.union(A)
print(C)

{0, 1, 2, 'a', 'f', 'e', 'o', 'c', 'b'}


# E1.union(E)
# E1.intersection(E)
# E2.difference(E)

In [5]:
# Ajouter un élémént à un ensemble 
B.add('z')
B

{0, 1, 2, 'a', 'b', 'c', 'o', 'z'}

In [9]:
# Ajouter plusieurs éléments dans un ensemble
A.update({5, 15, '3'})
A

{1, 15, 2, '3', 5, 'c', 'e', 'f'}

In [12]:
# Supprimer un élément dans un ensemble
# B.remove('y')
if 'y' in B:
    B.remove('y')
else:
    print("Y n'appartient pas à B")

# B.discard('y')

Y n'appartient pas à B


In [13]:
# pop supprime le dernier élément ou de façon aléatoire
A.pop()
A

{15, 2, '3', 5, 'c', 'e', 'f'}

In [25]:
B

{0, 1, 2, 'a', 'b', 'c', 'o', 'z'}

In [26]:
# La différence de deux ensembles
C = {1, 2, 3, 5}
D = {2, 4, 6, 7}

D.difference(C)

{4, 6, 7}

In [27]:
C.difference(D)

{1, 3, 5}

In [29]:
# Afficher les diviseurs d'un nombre
n = int(input("Donnez un entier: "))
for i in range(1, (n-1)//2):
    if(n%i == 0):
        print(i)
print(n)


Donnez un entier: 12
1
2
3
4
12


In [33]:
# Les dictionnaires
pays = {"Gabon":"Libreville", "Congo":"Brazzaville", "Tchad":"N'djamena"}
pays

{'Gabon': 'Libreville', 'Congo': 'Brazzaville', 'Tchad': "N'djamena"}

In [35]:
# Parcourir un dictionnaire et accéder aux éléments du dictionnaire
# pays.keys()
# pays.value()
# pays.items

#for keys, values in pays.items():
    #print(keys,':',values)
# ou

for p, c in pays.items():
    print(p, "a pour capitale, ", c)

Gabon a pour capitale,  Libreville
Congo a pour capitale,  Brazzaville
Tchad a pour capitale,  N'djamena


In [36]:
# Ajouter un élément dans un dictionnaire
pays['Benin'] = 'Cotonu'
pays

{'Gabon': 'Libreville',
 'Congo': 'Brazzaville',
 'Tchad': "N'djamena",
 'Benin': 'Cotonu'}

In [37]:
# Modifier un élément dans un dictionnaire
pays['Benin'] = 'Portonovo'
pays

{'Gabon': 'Libreville',
 'Congo': 'Brazzaville',
 'Tchad': "N'djamena",
 'Benin': 'Portonovo'}

In [39]:
for k in pays:
    print(pays[k])


Libreville
Brazzaville
N'djamena
Portonovo


In [40]:
# Acceder un élément
pays['Benin']
pays.get('Benin')

'Portonovo'

In [41]:
pays.get('Niger', "n'existe pas")

"n'existe pas"

In [42]:
pays.get('Congo', "n'existe pas")

'Brazzaville'

In [44]:
p = input("Donnez un pays: ")
pays.get(p, "n'existe pas")

Donnez un pays: USA


"n'existe pas"

In [51]:
# pays.pop()

# Enlever un élément dans un dictionnaire de façon aléatoire
# pays.popItem()

L = (1, 2, 5, 7, '1', 2, 5, 7, 3)
T = list(L);T

[1, 2, 5, 7, '1', 2, 5, 7, 3]

In [52]:
# Enlève les doublants 
E = set(L)
E

{1, '1', 2, 3, 5, 7}

In [56]:
# d = dist(nom="Maty", prenom="Maty", age=49)

# Les fonctions

In [55]:
# def nomFonction(les des paramètres):
    # corps de fonctions
    # return les valeurs

def diviseurs(n):
    for i in range(1, (n + 1)//2):
        if n%i==0:
            print(i, end="")
print(n)

a = int(input("Donnez un entier: "))
diviseurs(a)

12
Donnez un entier: 5
1

In [58]:
def calculs(a, b, c):
    S = a + b + c
    M = S/3
    P = a * b * c
    return S, M, P

calculs(2, 4, 5)

(11, 3.6666666666666665, 40)

In [60]:
def calcul(*a):
    if len(a):
        S = 0
        P = 1
        for e in a:
            S += e
            P *= e
        M = S / len(a)
    return (S, P, M)
calcul(5, 3)

    

(8, 15, 4.0)

In [66]:
calcul(2, 4, 5, 3, 2, 5)

(21, 1200, 3.5)

In [68]:
# La recursité est une fonction qui s'appelle elle-même
calcul(2, 4, 5, 3, 2, 5)

(21, 1200, 3.5)

In [70]:
def facto(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * facto(n - 1)
facto(5)

120

In [4]:
def puplet(*l): # args
    if len(l):
        for e in l:
            print(e, end=" ")
    else:
        print("Pas de paramètre")
    
puplet(1, 3, 10)    

# Appelle de la fonction
puplet([5, 10, 15, 0], 13, (3, 6, 8))
puplet(3)
peuplet()

1 3 10 [5, 10, 15, 0] 13 (3, 6, 8) 3 

In [6]:
# Fonction avec paramètre par défaut
def somme(a, b, c):
    return a + b + c
# Appelle de la fonction
somme(2, 4, 8) # => 14

14

In [9]:
# Fonction avec paramètre par défaut
def somme(a, b = 3, c = 5):
    return a + b + c
# Appelle de la fonction
somme(4) # => 12

12

In [10]:
# Fonction avec paramètre par défaut
def somme(a, b = 3, c = 5):
    return a + b + c
# Appelle de la fonction
somme(4, 6) # => 14

15

In [11]:
# Fonction avec paramètre par défaut
def somme(a, b = 3, c = 5):
    return a + b + c
# Appelle de la fonction
somme(4, c = 6) # => 14

13

In [13]:
# Fonction avec paramètre par défaut
def somme(a, b = 3, c = 5): #keyword
    return a + b + c
# Appelle de la fonction
somme(b = 10, a = 4, c = 2) # => 14

16

In [16]:
def diko(**kwargs):
    for k, v in kwargs.items():
        print(k, '->', v)
diko(Nom="Maty", Prenom="Maman", Age=49)
diko(Nom="AP/LP3", Annee="2019-2020", Lieu="IAI")

Nom -> Maty
Prenom -> Maman
Age -> 49
Nom -> AP/LP3
Annee -> 2019-2020
Lieu -> IAI
