In [1]:
import numpy as np

In [2]:
L=[1,2,5,7,2,8,9,1,9]

In [3]:
S=np.array(L)

In [4]:
S.sum()

44

In [5]:
S.mean()

4.888888888888889

In [6]:
S.std()

3.2470309324894346

In [7]:
S.std(ddof=1)

3.443996386628637

In [8]:
S.var()

10.543209876543209

In [9]:
S.var(ddof=1)

11.861111111111109

In [10]:
S.min()

1

In [11]:
S.max()

9

In [38]:
np.median(S)

5.0

In [13]:
np.quantile(S,[0.25,0.5,0.75])

array([2., 5., 8.])

# Opérations surs les matices

In [16]:
S.T

array([1, 2, 5, 7, 2, 8, 9, 1, 9])

In [17]:
I=np.eye(3)

In [18]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
I+1

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [20]:
I*2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [21]:
I**2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
I@I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
M=np.random.randint(0,20,(5,5))
M

array([[ 5, 18, 18,  3,  6],
       [16,  0,  6,  1,  3],
       [17, 11, 17, 14, 10],
       [10, 15,  7,  1, 19],
       [ 4,  2, 16, 14, 19]])

In [24]:
M.T

array([[ 5, 16, 17, 10,  4],
       [18,  0, 11, 15,  2],
       [18,  6, 17,  7, 16],
       [ 3,  1, 14,  1, 14],
       [ 6,  3, 10, 19, 19]])

In [25]:
U=np.triu(M)

In [26]:
U

array([[ 5, 18, 18,  3,  6],
       [ 0,  0,  6,  1,  3],
       [ 0,  0, 17, 14, 10],
       [ 0,  0,  0,  1, 19],
       [ 0,  0,  0,  0, 19]])

In [27]:
L=np.tril(M)
L

array([[ 5,  0,  0,  0,  0],
       [16,  0,  0,  0,  0],
       [17, 11, 17,  0,  0],
       [10, 15,  7,  1,  0],
       [ 4,  2, 16, 14, 19]])

In [28]:
det=np.linalg.det(M)
det

-952460.0000000008

In [29]:
IM=np.linalg.inv(M)
IM

array([[-0.02011633,  0.0434034 ,  0.02334586,  0.01006656, -0.0228545 ],
       [ 0.00476135, -0.06168238,  0.0500588 ,  0.0307593 , -0.04887029],
       [ 0.07077988,  0.06101044, -0.06246667, -0.04528379,  0.04617622],
       [-0.05352456, -0.08388804,  0.10407996, -0.01016736, -0.0144636 ],
       [-0.01643114,  0.00779035, -0.03427126,  0.04026836,  0.03435945]])

In [30]:
IM

array([[-0.02011633,  0.0434034 ,  0.02334586,  0.01006656, -0.0228545 ],
       [ 0.00476135, -0.06168238,  0.0500588 ,  0.0307593 , -0.04887029],
       [ 0.07077988,  0.06101044, -0.06246667, -0.04528379,  0.04617622],
       [-0.05352456, -0.08388804,  0.10407996, -0.01016736, -0.0144636 ],
       [-0.01643114,  0.00779035, -0.03427126,  0.04026836,  0.03435945]])

In [4]:
# Transposée d'une matrice
import numpy as np
Q = np.array([[1, 2, 3], [2, 1, 0], [3, 1, 1]])
Q

array([[1, 2, 3],
       [2, 1, 0],
       [3, 1, 1]])

In [5]:
# Transposée
Q.T

array([[1, 2, 3],
       [2, 1, 1],
       [3, 0, 1]])